#!/bin/bash
#
# kasutajate nimekiri kujul Perenimi, Eesnmimi
#
# skripti algus
#
who | cut -f1 -d" " | cut -f2 -d"." > perenimi #lõikame perenimi - see on 2. element peale punkti ja salvestama faili
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikame eesnimi - see on 1. element ennem punkti ja salvestame faili
paste -d"." perenimi eesnimi > nimed  #kleebime need failid vastavas järjekorras kokku
awk {print} nimed | sort
#
# skripti lõpp
